"""Generate a showcase README in the output folder, embedding the charts + data sources.

Writes ``<out_dir>/README.md`` (default ``data/trust/README.md``) so the output folder is a
self-contained, GitHub-renderable showcase: it embeds each generated chart and lists the exact
data sources, both derived from the data actually produced (``trust_combined_long.csv`` +
``manifest.json``) so the showcase can never claim a source the data did not carry.
"""

from __future__ import annotations

import csv
import json
import os
from typing import Iterable

from . import citations, metrics


def _load_rows(long_csv: str) -> list[dict]:
    with open(long_csv, newline="") as fh:
        rows = list(csv.DictReader(fh))
    for r in rows:
        r["year"] = int(r["year"])
        r["value"] = float(r["value"])
    return rows


def _reference_for(source: str) -> str:
    return citations.full_citation(source)


def write_showcase(
    out_dir: str,
    long_csv: str | None = None,
    manifest_json: str | None = None,
    chart_files: Iterable[str] | None = None,
) -> str:
    """Write ``<out_dir>/README.md`` embedding charts + sources. Returns the path."""
    long_csv = long_csv or os.path.join(out_dir, "trust_combined_long.csv")
    manifest_json = manifest_json or os.path.join(out_dir, "manifest.json")
    rows = _load_rows(long_csv)

    manifest = {}
    if os.path.exists(manifest_json):
        with open(manifest_json) as fh:
            manifest = json.load(fh)

    # Per-metric coverage + the source(s) recorded on those exact rows.
    lines: list[str] = []
    lines.append("# Trust in UK government over time — data & figures\n")
    lines.append(
        "UK-first with EU-27 + US comparators. Generated by "
        "[`fetch_trust.py`](../../fetch_trust.py); see "
        "[`trust_data/README.md`](../../trust_data/README.md) for full method notes.\n"
    )
    span = f"{manifest.get('year_min', '?')}–{manifest.get('year_max', '?')}"
    lines.append(
        f"**Coverage:** {span} · **{manifest.get('n_rows', len(rows))} rows** · "
        f"{len({r['iso3'] for r in rows})} countries.\n"
    )

    # Data sources (only those actually present in the data).
    lines.append("## Data sources & citations\n")
    lines.append(
        "Every value is fetched from, or traceable to, the sources below \u2014 credited to the "
        "organisation that collected the data. Nothing is hand-authored or estimated. Each "
        "figure also prints a short citation as a caption.\n"
    )
    for src in sorted({r["source"] for r in rows}):
        lines.append(f"- {_reference_for(src)}")
    lines.append("")

    # One section per metric, embedding the chart and its coverage/source.
    lines.append("## Figures\n")
    charts_present = {os.path.splitext(os.path.basename(p))[0] for p in (chart_files or [])}
    for metric_id, meta in metrics.METRICS.items():
        sub = [r for r in rows if r["metric"] == metric_id]
        if not sub:
            continue
        srcs = sorted({r["source"] for r in sub})
        lo, hi = min(r["year"] for r in sub), max(r["year"] for r in sub)
        chart_rel = f"charts/{metric_id}.png"
        chart_exists = metric_id in charts_present or os.path.exists(
            os.path.join(out_dir, chart_rel)
        )
        lines.append(f"### {meta.label}\n")
        lines.append(f"*{meta.description}*\n")
        if chart_exists:
            lines.append(f"![{meta.label}]({chart_rel})\n")
        lines.append(
            f"- **Unit:** {meta.unit} (higher = more trust) · **Coverage:** {lo}–{hi}"
        )
        lines.append(f"- **Source:** {'; '.join(_reference_for(s) for s in srcs)}\n")

    lines.append("## Files in this folder\n")
    lines.append("- `trust_combined_long.csv` / `trust_combined_wide.csv` — tidy data tables")
    lines.append("- `manifest.json` — run metadata (row counts, year span, source list)")
    lines.append("- `raw/manual_trust.csv` — OECD survey seed (verbatim from Our World in Data)")
    lines.append("- `charts/*.png` — the figures above")
    lines.append("- `processed/trust_summary.csv` — UK trend summary\n")

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "README.md")
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))
    return out_path
